config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :notifications, only: [:index,:update]
  resources :posts
  resources :accounts, as: :users, only: [:show, :update]
  resources :friendships, only: [:create,:update,:index]
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  get 'main/home'
  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
  	root 'main#unregistered'
  end



  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :set_user
	before_action :authenticate_user!, only: [:update]
	before_action :authenticate_owner!, only: [:update]
	
	def show
		@are_friends = current_user.my_friend?(@user)
	end

	def update
		respond_to do |format|
			if @user.update(user_params)
				format.html{redirect_to @user}
				format.json{ render :show}
				format.js
			else
				format.html{redirect_to @user, notice:@user.errors.full_messages}
				format.json{ render json: @user.errors}
			end
		end
	end

	private

		def set_user
			@user = User.find(params[:id])
		end

		def authenticate_owner!
			if current_user != @user
				redirect_to root_path, notice: "no", status: :unauthorized
			end
		end

		def user_params
			params.require(:user).permit(:name,:email,:username,:last_name,:bio, :cover,:avatar)
		end
end

app/views/accounts/_menu_avatar.haml
.absolute{style:"top: 20px;right: 20px;"}
	%button.mdl-button.white-text.mdl-js-button#user-menu-avatar-left 	
		Cambiar foto
	%ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect{for:"user-menu-avatar-left"}
		%li.mdl-menu__item.file-activate{for:"#user_avatar"} Actualizar foto de perfil
		%li.mdl-menu__item.file-activate{for:"#user_cover"} Actualizar portada

app/views/accounts/show.haml
.margin-xy
	.row.center-xs
		.col-xs-8.col-md-10
			.white.mdl-shadow--2dp.top-space.relative
				.big-padding.white-text.text-left.cover.relative#user-cover{style:"background-image:url(#{@user.cover.url("medium") })"}
					=render "accounts/menu_avatar"
					.top-space#user-avatar
						=circle_img @user.avatar.url(:medium),100
				%section.border-bottom.top-space
					.row.middle-xs
						.col-xs-12
							%h1.no-margin.medium.center-xs
								%span.medium= best_in_place_if current_user == @user, @user, :name,:place_holder => "Click me to add a name"
								%span.medium= best_in_place_if current_user == @user, @user, :last_name,:place_holder => "Click me to add a last name"

								%p.medium
									%span= best_in_place_if current_user == @user, @user, :username,:place_holder => "Click me to add a username"
						.col-xs-4.col-sm-2
							-unless @are_friends
								=button_to friendships_path(friend_id:@user.id), method: :post, remote: true, :"data-type" => "script", class:"mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect" do
									%i.material-icons person_add

				.large-padding
					.row
						.col-xs
							%h4 Seguidores
							%h5
								=@user.followers.count
						.col-xs
							%h4 Posts
							%h5
								=@user.posts.count
					.row.center-xs
						.col-xs-8.col-md-10
							%h4 Biography
							%span.medium= best_in_place_if current_user == @user, @user, :bio,:place_holder => "Click me to add a biography",class:'black-text'
			.top-space
				=form_for @user, remote: true do |f|
					%div{style:"display:none"}
						=f.file_field :avatar,class:"remotipart"
				=form_for @user, remote: true do |f|
					%div{style:"display:none"}
						=f.file_field :cover,class:"remotipart"